# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:12
from __future__ import unicode_literals

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='', max_length=100, unique=True, validators=[apps.user.models.validateLength])),
                ('first_name', models.CharField(max_length=100, validators=[apps.user.models.validateLength])),
                ('last_name', models.CharField(max_length=100, validators=[apps.user.models.validateLength])),
                ('password', models.CharField(max_length=255, validators=[apps.user.models.validateLength])),
                ('doh', models.DateField(default='2012-12-12')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('avatar', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
