# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20161220_2250'),
        ('appointments', '0002_auto_20161221_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('address_primary', models.CharField(max_length=50)),
                ('address_street', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('allow_others', models.BooleanField(default=False)),
                ('creater_approve_other_invites', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Address')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Invited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('check_if_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('to_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
        migrations.AddField(
            model_name='comment',
            name='related_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Message'),
        ),
    ]
