# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170109_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.Address'),
            preserve_default=False,
        ),
    ]
