# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 22:50
from __future__ import unicode_literals

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='doh',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alias',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True, validators=[apps.user.models.validateLength]),
        ),
    ]
