# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 04:26
from __future__ import unicode_literals

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True, validators=[apps.users.models.validateLength]),
        ),
    ]
